#!/bin/sh

# 상대경로는 resolve 안됨
resolve_link() {
	target="$1"
	while [ -h "$target" ]; do
		target=$(readlink "$target")
	done
	echo "$target"
}

time="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
fd --type symlink --max-depth 1 . ~/.config | while read -r symlink; do
	# dst=$(resolve_link "$symlink")
	# if [ ! -e "$dst" ]; then
	# 	echo "rm $symlink $dst"
	# 	# rm "$symlink"
	# fi
done

fd --type symlink --max-depth 1 . ~/.local/share | while read -r symlink; do
	dest=$(resolve_link "$symlink")
	if [ ! -e "$dest" ]; then
		# echo "rm $symlink"
		rm "$symlink"
	fi
done
