[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "C901",    # too-complex
  "PLR0915", # too-many-statement
  # "PLR2004", # magic-value-comparison
  # "INP", # implicit-namespace-package
  "S603", # subprocess-without-shell-equals-true

  # Things might be enabled for production code:
  "EXE",    # flake8-executable
  "D",      # pydocstyle
  "TRY",    # tryceratops
  "T20",    # flake8-print
  "ANN",    # flake8-annotations
  "TD",     # flake8-todos
  "ERA001", # commented-out-code

  # styles
  "RET504", # unnecessary-assign

  # not useful
  "RUF001", # ambiguous-unicode-character-string
  "RUF002", # ambiguous-unicode-character-docstring
  "RUF003", # ambiguous-unicode-character-comment

  # Things can be fixed by formatter:
  "I",   # isort
  "COM", # flake8-commas
  "Q",   # flake8-quotes
  "W",   # pycodestyle - warning

  # Things can be fixed by formatter #2:
  "W293", # blank-line-with-whitespace
  "E501", # line-too-long
  "Q000", # bad-quotes-inline-string
  "Q001", # bad-quotes-multiline-string
  "Q002", # bad-quotes-docstring
  "D201", # no-blank-line-before-function
  "D202", # no-blank-line-after-function
  "D203", # one-blank-line-before-class
  "D204", # one-blank-line-after-class
  "D205", # blank-line-after-summary
  "D206", # indent-with-spaces
  "D209", # new-line-after-last-paragraph
  "D210", # no-surrounding-whitespace
  "D211", # no-blank-line-before-class
]

[tool.ruff.pydocstyle]
convention = "pep257"

[tool.black]
line-length = 79
