---
smb-user-password: ENC[AES256_GCM,data:mE4D0uzIO78csg12c0xE7K39OWfGOPvN5UbJbqBIUd6pbdGQQeQFMRw=,iv:bPmaliSjpqBEePoRhgehyoCtcyvx7KRM3s3FP1rXkmo=,tag:uw155z8tS9WNWwLXhoatpg==,type:str]
smb-user-credentials: ENC[AES256_GCM,data:FoMSVkXzz6hhqFGFCrZi9A0Kwxu7jz9al9qZigGkhEOywCCsbpLv2+z3iZQg68UnbBaWvvWs+LY+DTIvI+1HUow=,iv:F+2K/mXxxXbv59S24zerVZwNRL84ETB8vRS0BDNaJBc=,tag:nn0dn8HqHKbKpGS4P/GPvg==,type:str]
sops:
  age:
    - recipient: age1yk5lf2dm7smps9kysmasrnu9qcefk7spdgaah3h2yuprgs225vgqlr33pv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjb0hpTmprZFRZNEJWamlr
        Q3FOemUwUnkvQ1A4N052UXhFdlhsR0FkdjFjCnh6VjBVRWJnQlNNcnk2YW9jVzJX
        Szg1dFlmeE5kVlM3dXNzdmVmaHh0QlEKLS0tIEk0OVZiTmVqeGNRTnFnNDBoZDZZ
        bjdra05Kbm5MMU1tZ1JOTW0zcVJZeUUKVUdPFI55+tJvLHBqhGJgbHBNo7EFyFo5
        s/Mt9geE6vblMbtAMsggoRwYNhcy3SXdbvh1ssaLkIc0tkTQ81zH6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-08-25T10:00:24Z'
  mac: ENC[AES256_GCM,data:AMuf8FHqdo22Jq2X1GncF/TJktmHmPU8syLIz8y7R8Yj3wrqLpXg9quQTTM129r27FF7+p43jkXVL0aXFHEgs11TY9h6CSTz8xhpJ9MQP7LeYyNxR5ZF+o7m4BmJ79w+pVXWxsd2KZOs4xacotbFW7wbQa8vSDA036UTxGDLQHo=,iv:9UYRB2McimhoyB0IbiMFg9owbbhh5cn/iMTQzz48YC4=,tag:ioaaZ3onVF11yaP9omaEnw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
