---
# NOTE:
# use age key for deploy/decrypt
# requires private age key in ~/.config/sops/age/keys.txt
# tl;dr: `sops path/to/secret/file.yaml` (which will open sops file in editor)
keys: [&home-age age1yk5lf2dm7smps9kysmasrnu9qcefk7spdgaah3h2yuprgs225vgqlr33pv]
creation_rules:
  - path_regex: ^(.*/)?secrets/[^/]+\.(yaml|json|jsonc|env|ini)$
    key_groups:
      - age: [*home-age]
  - path_regex: .*
    key_groups:
      - age: [*home-age]
