[project]
name = "nix-gc-sysgen"
description = ""
version = "0.1.0"

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[project.scripts]
nix-gc-sysgen = "nix_gc_sysgen:entrypoint"
