daemon:
  modules:
    - Xim
    # - Indicator
    # - Wayland
indicator:
  icon_color: Dark
log:
  global_level: INFO
engine:
  latin:
    preferred_direct: true
  hangul:
    layout: sebeolsik-3-91
    word_commit: false
    addons:
      all:
        - ComposeChoseongSsang
        - FlexibleComposeOrder
  default_category: Latin
  global_category_state: false
  global_hotkeys:
    M-C-Backslash:
      behavior:
        Mode: Math
      result: ConsumeIfProcessed
    M-C-E:
      behavior:
        Mode: Emoji
      result: ConsumeIfProcessed
    Muhenkan:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
    AltR:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
    Hangul:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
  category_hotkeys:
    Hangul:
      HangulHanja:
        behavior:
          Mode: Hanja
        result: Consume
      F9:
        behavior:
          Mode: Hanja
        result: ConsumeIfProcessed
  mode_hotkeys:
    Math:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Hanja:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Emoji:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
  xim_preedit_font:
    - Monospace
    - 15.0
