#!/bin/sh

# Usage: mkcd <id> <args>

id="$1"
shift

big_arg=""
for arg in "$@"; do
  big_arg="${big_arg} ${arg}"
done

big_arg="$(echo "${big_arg}" | xargs)"

[ ! -d "$big_arg" ] && mkdir "$big_arg"

lf -remote "send \"$id\" cd \"$big_arg\""
