#!/usr/bin/env python3

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

LF_ID = os.environ["id"]  # noqa: SIM112


def lf_send(command: str) -> None:
    lf_send_arg = ["lf", "-remote", f"send {LF_ID} {command}"]
    print(lf_send_arg)
    subprocess.run(lf_send_arg, check=True)


def main(file: Path) -> int:
    # file: Path = Path(argv[0])

    if file.is_dir():
        lf_send("push :rename<enter>")
        return 0

    command_raw: list[str] = ["push :rename<enter>"]
    command_raw.extend(["<c-b>" for _ in range(len(file.suffix))])
    lf_send("".join(command_raw))
    return 0


if __name__ == "__main__":
    # Usage:
    # <rename.py> <file>

    # Use shell-async in lf
    sys.exit(main(Path(sys.argv[1])))
