#!/usr/bin/env -S just --justfile

set fallback := true

_:
    @just --list

help:
    python3 -m zfs_snapshot_prune --help

test:
    python3 -m zfs_snapshot_prune -r isis/safe/varlib --keep-within-hourly P1D --filter "^zrepl_.*"

build:
    nix-build

uv-build:
    uv build
