ddclient-config: ENC[AES256_GCM,data:Skvm6nQxDO4GnGw4t99exNQ49nhfVFEDEisbJ6HbtdnxM+yQ1EojK00oUy5UkuGlhb5aIJ4yTrgdfL6Yw2Eu1dTR5TkBqrdNpJf69tAHgfAVAI9qbN++KQFlVzfYpGV5I+Ucm6O+7QZ4mRZUVzqDHpEMlks7iVH+4K9DJ7QQ+BxxS2+Ckqq2vZH7oq1zP0EOSjK9ZIpyypcvnjIdwInpAseyH2W9Rvn14eNuqc/BUcuYvtwptWAUwjVKcRZKoAHV+rHOEqgnuu/3JUSHLxIsg7QfmgZBGoLyBRGBoHa8AVmbRwq3Y2oMS3nPfzAel5+w4G8ItNjL1m8W1WEJqF3J6RrXo0ybnXCSXWsU+VFbfGUVGMGSDtnnoP3XdGZHol0=,iv:6o8OuXcKYK21AziIUsHyRuUUBMwnfgrK4BEn3zXzyF8=,tag:RWHCnN6JLcoU3YELQbSoFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yk5lf2dm7smps9kysmasrnu9qcefk7spdgaah3h2yuprgs225vgqlr33pv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c2RDbVNNbkoyTFdGTmY3
            SmFheWt5L29EYlhxTWhlek1kam9XRUs5akN3CndPTzJjWjBIOUYvdC8yYnVEejJH
            Ry9NWW5aQXlSYkR3bEMvT0RZcVl6YmsKLS0tIEpzMUt3UUhKcXB4YkpyMEFuaUZ5
            UFRTSW85dkMxd1g2amZMYWxqYnErbnMKRPWzbQ3cpaPDymCoIJiu9MhLOsvtZ6sV
            eKyc5kaRf9h+oJAfNYcekDqRXs1vB3dYFjg9wkUJ+KAK05ttR+vFMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T12:17:44Z"
    mac: ENC[AES256_GCM,data:Rfa2a5ZUlKJ+PTRQvs0Sx4labXbAnYl98T2CIo7tHSKIT6ZrNktV2sRVzMKu+ZQ9VLsZHNPTvr6E39cn3qw2H3vg2mAHcvbXTfadfFw2VVuKqTIyK51+1YSvpokNIyfHR230u1aA5ca7prmiV4bvWfxBBhBNmTYP3C2D02f+6s0=,iv:1X1aWQk38y/Ju5RDv7bh4ca2NckOKn+UpnpAr9h2IsI=,tag:kdhdMtKYCYVZuie+6h24Vw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
