#!/usr/bin/env bash

color00="30/30/30"          # Base 01 - Black
color01="ed/33/3b"          # Base 08 - Red
color02="57/e3/89"          # Base 0B - Green
color03="ff/78/00"          # Base 09 - Yellow
color04="62/a0/ea"          # Base 0D - Blue
color05="91/41/ac"          # Base 0E - Magenta
color06="5b/c8/af"          # Base 0C - Cyan
color07="de/dd/da"          # Base 06 - White
color08="9a/99/96"          # Base 02 - Bright Black
color09="f6/61/51"          # Base 12 - Bright Red
color10="8f/f0/a4"          # Base 14 - Bright Green
color11="ff/a3/48"          # Base 13 - Bright Yellow
color12="99/c1/f1"          # Base 16 - Bright Blue
color13="dc/8a/dd"          # Base 17 - Bright Magenta
color14="93/dd/c2"          # Base 15 - Bright Cyan
color15="f6/f5/f4"          # Base 07 - Bright White
color16="ff/78/00"          # Base 09
color17="a5/1d/2d"          # Base 0F
color18="30/30/30"          # Base 01
color19="5e/5c/64"          # Base 03
color20="fc/fc/fc"          # Base 04
color21="de/dd/da"          # Base 06
color_foreground="de/dd/da" # Base 05
color_background="1d/1d/1d" # Base 00

ansi_mappings=(
  Black
  Red
  Green
  Yellow
  Blue
  Magenta
  Cyan
  White
  Bright_Black
  Bright_Red
  Bright_Green
  Bright_Yellow
  Bright_Blue
  Bright_Magenta
  Bright_Cyan
  Bright_White
)
colors=(
  base00
  base08
  base0B
  base0A
  base0D
  base0E
  base0C
  base05
  base03
  base08
  base0B
  base0A
  base0D
  base0E
  base0C
  base07
  base09
  base0F
  base01
  base02
  base04
  base06
)
for padded_value in $(seq -w 0 21); do
  color_variable="color${padded_value}"
  eval current_color=\$"$color_variable"
  current_color=$(echo "${current_color//\//}" | tr '[:lower:]' '[:upper:]') # get rid of slashes, and uppercase
  non_padded_value=$((10#$padded_value))
  base16_color_name=${colors[$non_padded_value]}
  current_color_label=${current_color:-unknown}
  ansi_label=${ansi_mappings[$non_padded_value]}
  block=$(printf "\x1b[48;5;${non_padded_value}m___________________________")
  foreground=$(printf "\x1b[38;5;${non_padded_value}m$color_variable")
  printf "%s %s %s %-30s %s\x1b[0m\n" "$foreground" "$base16_color_name" "$current_color_label" "${ansi_label:-""}" "$block"
done
# if [ $# -eq 1 ]; then
#   printf "To restore current theme, source ~/.base16_theme or reopen your terminal\n"
# fi
#
