_: {
  imports = [
    ./nix
    ./chrony.nix
    ./console.nix
    ./containers.nix
    ./davfs2.nix
    ./dbus.nix
    ./env.nix
    ./firewall.nix
    ./fstrim.nix
    ./hardware.nix
    ./home-manager.nix
    ./keyboard.nix
    ./libvirtd.nix
    ./locale.nix
    ./network.nix
    ./pam.nix
    ./samba.nix
    ./shell.nix
    ./ssh.nix
    ./sysctl.nix
    ./systemd-tmpfiles.nix
    ./systemd.nix
    ./time.nix
    ./users.nix
    ./zram.nix
  ];
}
