# [terminal.shell]
# program = "zellij"

# [font]
# size = 10.0

[font.bold]
family = "MesloLGM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGM Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[window.padding]
x = 4
y = 4

[window]
dynamic_padding = false
decorations = "full"
dynamic_title = true

[window.dimensions]
columns = 90
lines = 30

[hints]
alphabet = "ntesiroahduflpyw,ckv.xmg"
