ddclient-config: ENC[AES256_GCM,data:2bEyF6jnS0n1pajXeZaneHIXaHdZasSXdpKriDdX/mUMO0DAtSY1xZwTwrvtfJKtiN+QVe+LVP8vhpuAcTjgnB2IQjVZx51I6+5qh6Y74/5ZtGSxJAgVsdRMKoLsmOASH5+ZZ/lWyZuLFID5yRXunOjtVi1kS/KJkwSATAn6XLVE823IVfwB3AoUuJJccFUMaZlymsSMwC9LeUmpWekTER7HRcwZZGXsGeE=,iv:Pc6QT2rBKwj6QsotsI+Pfl1xNiFNlxiX7gE6m+E50UI=,tag:FX5hGr4dFjLcLMzt5a63UA==,type:str]
sops:
    age:
        - recipient: age1yk5lf2dm7smps9kysmasrnu9qcefk7spdgaah3h2yuprgs225vgqlr33pv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c2RDbVNNbkoyTFdGTmY3
            SmFheWt5L29EYlhxTWhlek1kam9XRUs5akN3CndPTzJjWjBIOUYvdC8yYnVEejJH
            Ry9NWW5aQXlSYkR3bEMvT0RZcVl6YmsKLS0tIEpzMUt3UUhKcXB4YkpyMEFuaUZ5
            UFRTSW85dkMxd1g2amZMYWxqYnErbnMKRPWzbQ3cpaPDymCoIJiu9MhLOsvtZ6sV
            eKyc5kaRf9h+oJAfNYcekDqRXs1vB3dYFjg9wkUJ+KAK05ttR+vFMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T18:39:02Z"
    mac: ENC[AES256_GCM,data:fs+9iAbVcEvtvjnEHE8dGBYwRERkyS9A7smOvd2qu0ZJwPUSRtgHxLGGiTJHFtd112oc3A7MuwCFe8MqTSmJonXW4qTptNR1ahCj3bAJIc5TF40Rn84X1eZdf6yY8gZ+ilkhQgTTNi/skJWmWLjR/rCN5Q5lBiShhXxve+Ob14o=,iv:ObKJlEc42rC3dTKTh1IeBa+w2hFZo9VOFAlt9yHTnls=,tag:R82EBGTt2RFW5wdoNV6WrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
