#!/usr/bin/env -S just --justfile

PROJECT := "quick-start"

alias fmt := format
alias lint := check

_:
    @just --list

build:
    nix --no-warn-dirty --quiet --log-format raw build '.#quick-start'

test:
    cargo test

check:
    cargo clippy

format:
    cargo clippy --fix 2>/dev/null | true
    cargo fmt --all
