#!/usr/bin/env -S just --justfile

PROJECT := "quick-start"

alias fmt := format
alias lint := check

# system := `nix --extra-experimental-features nix-command eval --raw --impure --expr builtins.currentSystem`

_:
    @just --list

build:
    # nix --no-warn-dirty build '.#packages.{{ system }}.{{ PROJECT }}'
    nix --no-warn-dirty build '.#{{ PROJECT }}'

test:
    cargo test

check:
    cargo clippy

format:
    cargo clippy --fix 2>/dev/null | true
    cargo fmt --all
