#!/usr/bin/env -S just --justfile

set fallback := true

PROJECT := "rustic-btrfs"

alias fmt := format
alias lint := check

_:
    @just --list

build:
    nix --no-warn-dirty build '.#{{ PROJECT }}'

test:
    cargo test

check:
    cargo clippy

format:
    cargo clippy --fix 2>/dev/null | true
    cargo fmt --all
