#!/usr/bin/env -S just --justfile

set fallback := true

PROJECT := "rustic-btrfs"

alias fmt := format
alias lint := check

_:
    @just --list

build:
    nix --quiet --log-format raw --no-warn-dirty build '.#{{ PROJECT }}'

test:
    cargo --quiet test

check:
    cargo --quiet clippy

format:
    cargo --quiet clippy --fix 2>/dev/null | true
    cargo --quiet fmt --all
