#!/usr/bin/env -S just --justfile

set fallback := true

PROJECT := "rustic-btrfs"

alias fmt := format
alias lint := check

_:
    @just --list

build:
    nix --quiet --log-format raw --no-warn-dirty develop '.#{{ PROJECT }}' --command -- cargo --quiet build

build-nix:
    nix --quiet --log-format raw --no-warn-dirty build '.#{{ PROJECT }}'

test:
    @echo "Running library unit tests..."
    nix --quiet --log-format raw --no-warn-dirty develop '.#{{ PROJECT }}' --command -- cargo --quiet test --lib

test-integration:
    @echo "Running integration tests..."
    nix --quiet --log-format raw --no-warn-dirty develop '.#{{ PROJECT }}' --command -- cargo --quiet test --test workflow_test --test lock_test

check:
    cargo --quiet clippy

format:
    cargo --quiet clippy --fix 2>/dev/null | true
    cargo --quiet fmt --all
