#!/usr/bin/env -S just --justfile

set fallback := true

alias fmt := format

_:
    @just --list

build:
    nix build '.#autoaspm'

check: lint lsp test

test:
    direnv exec . pytest test_autoaspm.py -v

lint:
    direnv exec . ruff check

lsp:
    direnv exec . basedpyright

format:
    direnv exec . ruff check --fix
    direnv exec . ruff format
