#!/usr/bin/env -S just --justfile

set fallback := true

alias fmt := format
alias lint := check

_:
    @just --list

build:
    nix build '.#autoaspm'

check:
    direnv exec . ruff check
    direnv exec . ty check

test:
    direnv exec . pytest test_autoaspm.py -v

format:
    direnv exec . ruff check --fix
    direnv exec . ruff format
    direnv exec . shellharden --replace completions/autoaspm.bash
    direnv exec . shfmt --write completions/autoaspm.bash
