#!/usr/bin/env -S just --justfile

set fallback := true

alias fmt := format

_:
    @just --list

build:
    nix build '.#autoaspm'

check: lint typecheck test

test:
    direnv exec . pytest test_autoaspm.py -v

lint:
    direnv exec . ruff check

typecheck:
    direnv exec . ty check

format:
    direnv exec . ruff check --fix
    direnv exec . ruff format
    direnv exec . shellharden --replace completions/autoaspm.bash
    direnv exec . shfmt --write completions/autoaspm.bash
