#!/bin/sh

if ([ "$TERM_PROGRAM" = "ghostty" ] && command -v kitten >/dev/null 2>&1) ||
  [ "$TERM" = "xterm-kitty" ]; then
  exec kitten icat --clear --stdin no --transfer-mode memory </dev/null >/dev/tty
fi
